this is the About us page
techgirlshub/TechGirlsHub-Website pull request #9
Opened 2024-10-28 19:12 UTC by NolwaziNgcongo

2024-10-29 08:14 UTC, MlonziNolwazi commented on AboutUs/index.html
> +        <div class="social-icons">
please use icons

2024-10-29 08:16 UTC, MlonziNolwazi commented on AboutUs/index.html
> +            <li><a href="#">About Us</a></li>
please include the url links,  and  Feedback Rating link - url should be feedbackRating.php

2024-10-29 08:17 UTC, MlonziNolwazi commented on AboutUs/index.html
> +    <title>About Us</title>
Can we have this as "TechGirlsHub - About Us"

2024-10-29 08:18 UTC, MlonziNolwazi commented on AboutUs/index.html
> +    <div class="hero-image" style="background-image: url('');">
Avoid having unused code.

2024-10-29 08:20 UTC, MlonziNolwazi requested changes
Please do the requested changes before merging ur branch

2024-10-30 16:36 UTC, techgirlshub approved these changes

2024-10-30 16:37 UTC, merged